name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show current directory
      run: pwd

    - name: List files
      run: ls -la

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./authenticator
      run: npm install --legacy-peer-deps


    - name: Run tests
      working-directory: ./authenticator
      run: npm test

    - name: Build project
      working-directory: ./authenticator
      run: CI='' npm run build


    # Optional: deploy step
    # - name: Deploy
    #   run: |
    #     echo "Deploy to production server here"
